// ============================================================================
// Category Definitions
// ============================================================================

export interface CategoryDefinition {
  keywords: string[];
  domains: string[];
  description: string;
}

export const CATEGORY_DEFINITIONS: Record<string, CategoryDefinition> = {
  finance: {
    keywords: [
      "bank",
      "investing",
      "brokerage",
      "trading",
      "stock",
      "crypto",
      "credit card",
      "debit card",
      "loan",
      "mortgage",
      "savings",
      "checking",
      "account",
      "cashback",
      "dividend",
      "portfolio",
      "trade",
      "deposit",
      "withdrawal",
      "transfer",
      "dividend",
    ],
    domains: [
      "trading212.com",
      "robinhood.com",
      "webull.com",
      "public.com",
      "moomoo.com",
      "fidelity.com",
      "schwab.com",
      "etrade.com",
      "coinbase.com",
      "binance.com",
      "kraken.com",
      "gemini.com",
      "chase.com",
      "bankofamerica.com",
      "wellsfargo.com",
      "citi.com",
      "americanexpress.com",
      "capitalone.com",
      "discover.com",
    ],
    description:
      "Financial services, banking, investing, and trading platforms",
  },

  food_delivery: {
    keywords: [
      "food",
      "delivery",
      "meal",
      "restaurant",
      "dining",
      "grocery",
      "doordash",
      "ubereats",
      "grubhub",
      "postmates",
      "delivery",
      "takeout",
      "cuisine",
      "pizza",
      "sushi",
      "burger",
    ],
    domains: [
      "doordash.com",
      "ubereats.com",
      "grubhub.com",
      "postmates.com",
      "instacart.com",
      "gopuff.com",
      "delivery.com",
      "seamless.com",
    ],
    description: "Food delivery and meal services",
  },

  transportation: {
    keywords: [
      "ride",
      "taxi",
      "uber",
      "lyft",
      "transport",
      "travel",
      "commute",
      "scooter",
      "bike",
      "rental",
      "car",
      "vehicle",
      "mile",
      "trip",
    ],
    domains: [
      "uber.com",
      "lyft.com",
      "lime.bike",
      "bird.co",
      "spin.app",
      "zipcar.com",
      "turo.com",
      "getaround.com",
    ],
    description: "Transportation, ride-sharing, and mobility services",
  },

  travel: {
    keywords: [
      "hotel",
      "flight",
      "airbnb",
      "booking",
      "vacation",
      "trip",
      "travel",
      "stay",
      "accommodation",
      "airline",
      "resort",
      "expedia",
      "booking.com",
      "hostel",
      "motel",
    ],
    domains: [
      "airbnb.com",
      "booking.com",
      "expedia.com",
      "hotels.com",
      "kayak.com",
      "priceline.com",
      "trip.com",
      "agoda.com",
      "vrbo.com",
      "hostelworld.com",
      "skyscanner.com",
    ],
    description: "Travel, accommodation, and booking platforms",
  },

  shopping: {
    keywords: [
      "shop",
      "store",
      "discount",
      "coupon",
      "cashback",
      "save",
      "amazon",
      "ebay",
      "retail",
      "purchase",
      "buy",
      "sale",
      "deal",
      "offer",
      "promo",
      "voucher",
    ],
    domains: [
      "amazon.com",
      "ebay.com",
      "walmart.com",
      "target.com",
      "bestbuy.com",
      "costco.com",
      "rakuten.com",
      "retailmenot.com",
      "honey.com",
      "ibotta.com",
      "fetchrewards.com",
    ],
    description: "Shopping, retail, and cashback platforms",
  },

  cloud_storage: {
    keywords: [
      "cloud",
      "storage",
      "backup",
      "sync",
      "file",
      "data",
      "google drive",
      "dropbox",
      "onedrive",
      "icloud",
      "server",
      "hosting",
      "vps",
      "database",
      "cdn",
    ],
    domains: [
      "dropbox.com",
      "drive.google.com",
      "icloud.com",
      "onedrive.live.com",
      "box.com",
      "pcloud.com",
      "sync.com",
      "mega.nz",
      "aws.amazon.com",
      "cloud.google.com",
      "azure.microsoft.com",
      "digitalocean.com",
      "linode.com",
      "vultr.com",
    ],
    description: "Cloud storage, hosting, and infrastructure services",
  },

  communication: {
    keywords: [
      "phone",
      "mobile",
      "cell",
      "internet",
      "wifi",
      "broadband",
      "verizon",
      "at&t",
      "t-mobile",
      "sprint",
      "mint",
      "visible",
      "call",
      "text",
      "message",
      "chat",
      "voip",
    ],
    domains: [
      "verizon.com",
      "att.com",
      "t-mobile.com",
      "mintmobile.com",
      "visible.com",
      "cricketwireless.com",
      "metrobyt-mobile.com",
      "uscellular.com",
      "xfinity.com",
      "spectrum.com",
    ],
    description:
      "Mobile carriers, internet providers, and communication services",
  },

  entertainment: {
    keywords: [
      "streaming",
      "movie",
      "music",
      "video",
      "game",
      "gaming",
      "netflix",
      "spotify",
      "hulu",
      "disney",
      "hbo",
      "prime",
      "subscription",
      "watch",
      "listen",
      "play",
      "console",
    ],
    domains: [
      "netflix.com",
      "spotify.com",
      "hulu.com",
      "disneyplus.com",
      "hbomax.com",
      "primevideo.com",
      "youtube.com",
      "twitch.tv",
      "steam.com",
      "xbox.com",
      "playstation.com",
      "epicgames.com",
    ],
    description: "Streaming, gaming, and entertainment subscriptions",
  },

  health: {
    keywords: [
      "health",
      "fitness",
      "gym",
      "workout",
      "exercise",
      "wellness",
      "medical",
      "doctor",
      "pharmacy",
      "insurance",
      "vitamin",
      "peloton",
      "nike",
      "adidas",
      "under armour",
    ],
    domains: [
      "peloton.com",
      "nike.com",
      "adidas.com",
      "underarmour.com",
      "myfitnesspal.com",
      "strava.com",
      "fitbit.com",
      "whoop.com",
      "headspace.com",
      "calm.com",
      "noom.com",
      "weightwatchers.com",
    ],
    description: "Health, fitness, and wellness services",
  },

  education: {
    keywords: [
      "learn",
      "course",
      "class",
      "education",
      "study",
      "student",
      "university",
      "college",
      "school",
      "degree",
      "certification",
      "udemy",
      "coursera",
      "skillshare",
      "masterclass",
    ],
    domains: [
      "coursera.org",
      "udemy.com",
      "skillshare.com",
      "masterclass.com",
      "edx.org",
      "khanacademy.org",
      "duolingo.com",
      "codecademy.com",
      "linkedin.com/learning",
    ],
    description: "Online learning and educational platforms",
  },

  software: {
    keywords: [
      "software",
      "app",
      "application",
      "tool",
      "saas",
      "license",
      "subscription",
      "download",
      "install",
      "program",
      "service",
    ],
    domains: [
      "github.com",
      "gitlab.com",
      "notion.so",
      "slack.com",
      "zoom.us",
      "figma.com",
      "canva.com",
      "adobe.com",
      "microsoft.com",
    ],
    description: "Software, applications, and SaaS products",
  },

  referral: {
    keywords: [
      "refer",
      "referral",
      "invite",
      "friend",
      "sign up",
      "join",
      "new user",
      "first time",
      "bonus",
      "reward",
      "credit",
    ],
    domains: [],
    description: "General referral programs",
  },
};
