export { SERVICE_PATTERNS } from "./referral";
export { parseCommand, GENERIC_PATTERNS } from "./command";

export const DOMAIN_TO_SERVICE: Record<string, string> = {
  "picnic.app": "picnic",
  "doordash.com": "doordash",
  "ubereats.com": "ubereats",
  "grubhub.com": "grubhub",
  "uber.com": "uber",
  "lyft.com": "lyft",
  "li.me": "lime",
  "bird.co": "bird",
  "airbnb.com": "airbnb",
  "booking.com": "booking",
  "expedia.com": "expedia",
  "robinhood.com": "robinhood",
  "trading212.com": "trading212",
  "crypto.com": "crypto_com",
  "coinbase.com": "coinbase",
  "revolut.com": "revolut",
  "rakuten.com": "rakuten",
  "joinhoney.com": "honey",
  "ibotta.com": "ibotta",
  "dropbox.com": "dropbox",
  "google.com": "google_one",
  "pcloud.com": "pcloud",
  "discord.com": "discord",
  "discord.gg": "discord",
  "telegram.org": "telegram",
  "spotify.com": "spotify",
  "netflix.com": "netflix",
  "headspace.com": "headspace",
  "calibrate.com": "calibrate",
  "db.tt": "dropbox",
};
