/**
 * AI Gateway Types
 *
 * TypeScript interfaces for Cloudflare AI Gateway integration.
 * Covers request/response shapes, configuration, cost tracking,
 * and observability metrics.
 *
 * @module worker/lib/ai-gateway/types
 */

// ============================================================================
// Gateway Configuration
// ============================================================================

/**
 * Configuration for the AI Gateway client.
 * All fields have sensible defaults; only `gatewayUrl` is required
 * in practice (sourced from `AI_GATEWAY_URL` env var).
 */
export interface GatewayConfig {
  /** Full AI Gateway URL (e.g., https://gateway.ai.cloudflare.com/v1/{account}/{gateway}/{provider}) */
  gatewayUrl: string;
  /** Provider key for fallback when gateway is unavailable */
  providerApiKey?: string;
  /** Direct provider URL used only when gateway fails (failover) */
  fallbackUrl?: string;
  /** Enable semantic caching of identical requests */
  cacheEnabled: boolean;
  /** TTL in seconds for cached responses (default: 3600) */
  cacheTtlSeconds: number;
  /** Request timeout in milliseconds */
  timeoutMs: number;
  /** Maximum retry attempts for transient failures */
  maxRetries: number;
}

/**
 * Minimal subset of environment variables the gateway client reads.
 * Mirrors fields from `Env` in `worker/types/api.ts`.
 */
export interface GatewayEnv {
  AI_GATEWAY_URL?: string;
}

// ============================================================================
// Request / Response Shapes
// ============================================================================

/**
 * A generic LLM request to forward through the gateway.
 * Models the OpenAI chat completion schema, which Cloudflare AI Gateway proxies.
 */
export interface GatewayRequest {
  /** Model identifier (e.g., "gpt-4o", "claude-3-opus") */
  model: string;
  /** Chat messages */
  messages: Array<{ role: "system" | "user" | "assistant"; content: string }>;
  /** Sampling temperature (0-2) */
  temperature?: number;
  /** Maximum tokens to generate */
  max_tokens?: number;
  /** Whether to stream the response */
  stream?: boolean;
  /** Additional provider-specific parameters */
  [key: string]: unknown;
}

/**
 * Usage statistics returned by the provider and relayed through the gateway.
 */
export interface TokenUsage {
  /** Tokens consumed by the prompt */
  promptTokens: number;
  /** Tokens generated by the model */
  completionTokens: number;
  /** Total tokens (prompt + completion) */
  totalTokens: number;
}

/**
 * Cost breakdown per request (in USD, micro-precision).
 */
export interface CostBreakdown {
  /** Prompt cost in USD */
  promptCostUsd: number;
  /** Completion cost in USD */
  completionCostUsd: number;
  /** Total cost in USD */
  totalCostUsd: number;
}

/**
 * Standard response shape after proxying through the gateway.
 */
export interface GatewayResponse {
  /** Whether the request succeeded */
  ok: boolean;
  /** Parsed response body (provider-specific) */
  data: unknown;
  /** Token usage extracted from the response */
  usage: TokenUsage;
  /** Cost breakdown for the request */
  cost: CostBreakdown;
  /** HTTP status code from upstream */
  statusCode: number;
  /** Whether this response came from cache */
  cached: boolean;
  /** Whether this came from the fallback provider */
  failover: boolean;
  /** Latency in milliseconds */
  latencyMs: number;
}

// ============================================================================
// Observability
// ============================================================================

/**
 * Structured log entry for every gateway request.
 */
export interface GatewayRequestLog {
  /** ISO-8601 timestamp */
  timestamp: string;
  /** Model used */
  model: string;
  /** Prompt token count */
  promptTokens: number;
  /** Completion token count */
  completionTokens: number;
  /** Total cost in USD */
  costUsd: number;
  /** Request latency in milliseconds */
  latencyMs: number;
  /** Whether the request hit the cache */
  cached: boolean;
  /** Whether failover was used */
  failover: boolean;
  /** HTTP status code from upstream */
  statusCode: number;
  /** Error message if the request failed */
  error?: string;
}

// ============================================================================
// Cache
// ============================================================================

/**
 * Cache key structure for semantic deduplication.
 */
export interface CacheKey {
  /** Model name */
  model: string;
  /** Stringified messages array */
  messagesHash: string;
  /** Temperature (rounded to 1 decimal) */
  temperature: number;
}
