#!/usr/bin/env bash
# Captures a lesson learned with structured prompts

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

cd "${ROOT_DIR}"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <lesson-title>"
    echo "Example: $0 \"Circuit Breaker Pattern for Deal Sources\""
    exit 1
fi

DATE=$(date +%Y-%m-%d)
SLUG=$(echo "$1" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')
LESSON_FILE="reports/lessons/${DATE}-${SLUG}.md"

mkdir -p reports/lessons

cat > "$LESSON_FILE" << LESSON_EOF
# Lesson Learned: $1

**Date**: ${DATE}
**Author**: $(git config user.name || echo "Agent")

## Context
<!-- Describe the situation that led to this lesson -->

## Discovery
<!-- What was learned? Be specific. -->

## Impact
<!-- Why does this matter? What problems does it solve or prevent? -->

## Action Items
<!-- Concrete steps to apply this lesson going forward -->
- [ ] 

## Related Files
<!-- Links to relevant code, docs, or issues -->
- 

## Tags
<!-- Categorize this lesson -->
Tags: #pattern #bug #optimization #architecture

---
*Generated by learn skill*
LESSON_EOF

echo "📝 Lesson captured: $LESSON_FILE"
echo "✏️  Edit the file to complete the template"
