#!/bin/bash
# KV Initialization Script for Deal Discovery System
# Generated by deploy-prep-agent
# Usage: ./init-kv-data.sh [environment]

set -e

ENV="${1:-production}"
NAMESPACE_ID="be3c0fc148b749b49a59aa7cfa23e3ac"

echo "🔧 Initializing KV Data for Deal Discovery System"
echo "Environment: $ENV"
echo "Namespace ID: $NAMESPACE_ID"
echo ""

# Verify wrangler is available
if ! command -v npx &> /dev/null; then
    echo "❌ Error: npx not found. Please install Node.js and npm."
    exit 1
fi

# Check if wrangler is installed
if ! npx wrangler --version &> /dev/null; then
    echo "❌ Error: wrangler not found. Run: npm install"
    exit 1
fi

echo "✓ Wrangler CLI detected"
echo ""

# Step 1: Seed source registry
echo "📦 Step 1: Seeding source registry..."
REGISTRY_DATA='[{"domain":"trading212.com","trust_initial":0.7,"active":true}]'

if [ "$ENV" == "production" ]; then
    npx wrangler kv key put \
        --namespace-id "$NAMESPACE_ID" \
        "registry" \
        "$REGISTRY_DATA"
else
    npx wrangler kv key put \
        --namespace-id "$NAMESPACE_ID" \
        --env "$ENV" \
        "registry" \
        "$REGISTRY_DATA"
fi

echo "✓ Source registry initialized"
echo ""

# Step 2: Verify the data
echo "🔍 Step 2: Verifying registry data..."
if [ "$ENV" == "production" ]; then
    VERIFY_OUTPUT=$(npx wrangler kv key get \
        --namespace-id "$NAMESPACE_ID" \
        "registry" 2>&1)
else
    VERIFY_OUTPUT=$(npx wrangler kv key get \
        --namespace-id "$NAMESPACE_ID" \
        --env "$ENV" \
        "registry" 2>&1)
fi

if echo "$VERIFY_OUTPUT" | grep -q "trading212.com"; then
    echo "✓ Registry data verified"
    echo "Content: $REGISTRY_DATA"
else
    echo "❌ Error: Failed to verify registry data"
    echo "Output: $VERIFY_OUTPUT"
    exit 1
fi

echo ""
echo "✅ KV Data Initialization Complete!"
echo ""
echo "Next steps:"
echo "  1. Verify data: npx wrangler kv key get --namespace-id $NAMESPACE_ID registry"
echo "  2. Add more sources by updating this script"
echo "  3. Deploy worker if not already deployed"
