#!/bin/bash
# Deployment Verification Script
# Generated by deploy-prep-agent
# Usage: ./verify-deployment.sh <subdomain> [environment]
# Set SMOKE_TEST_API_KEY env var for authenticated endpoints (admin role required)

set -e

SUBDOMAIN="${1:-do-deal-relay}"
ENV="${2:-production}"

if [ -z "$SUBDOMAIN" ]; then
    echo "❌ Error: Subdomain required"
    echo "Usage: ./verify-deployment.sh <subdomain> [staging|production]"
    exit 1
fi

# Build auth header for protected endpoints
AUTH_HEADER=""
if [ -n "${SMOKE_TEST_API_KEY}" ]; then
    AUTH_HEADER="-H X-API-Key:${SMOKE_TEST_API_KEY}"
else
    echo "⚠️  SMOKE_TEST_API_KEY not set — authenticated endpoints will be skipped"
fi

if [ "$ENV" == "staging" ]; then
    URL="https://do-deal-relay-staging.$SUBDOMAIN.workers.dev"
    echo "🔍 Verifying STAGING deployment"
else
    URL="https://do-deal-relay.$SUBDOMAIN.workers.dev"
    echo "🔍 Verifying PRODUCTION deployment"
fi

echo "URL: $URL"
echo ""

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "⚠️  Warning: jq not found. Responses will not be pretty-printed."
    echo "   Install jq for better output: https://stedolan.github.io/jq/download/"
    JQ_AVAILABLE=false
else
    JQ_AVAILABLE=true
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Testing 8 API Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

FAILED=0

# Test 1: Health endpoint
echo "1️⃣  GET /health"
RESPONSE=$(curl -s -w "\n%{http_code}" "$URL/health")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        echo "$BODY" | jq -C '.' | sed 's/^/   /'
        # Verify status is healthy
        if echo "$BODY" | jq -e '.status == "healthy"' > /dev/null 2>&1; then
            echo "   ✓ Status: healthy"
        else
            echo "   ⚠️  Status: $(echo "$BODY" | jq -r '.status')"
        fi
    else
        echo "   $BODY"
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 2: Metrics endpoint (requires auth)
echo "2️⃣  GET /metrics"
RESPONSE=$(curl -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/metrics")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if echo "$BODY" | grep -q "deals_" > /dev/null 2>&1; then
        echo "   ✓ Prometheus metrics found"
    fi
    # Show first few lines
    echo "$BODY" | head -6 | sed 's/^/   /'
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 3: Deals endpoint (requires auth)
echo "3️⃣  GET /deals"
RESPONSE=$(curl -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/deals")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        COUNT=$(echo "$BODY" | jq '. | length')
        echo "   ✓ $COUNT deals returned"
    else
        echo "   $BODY"
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 4: Deals JSON endpoint (requires auth)
echo "4️⃣  GET /deals.json"
RESPONSE=$(curl -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/deals.json")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        if echo "$BODY" | jq -e '.schema_version' > /dev/null 2>&1; then
            SCHEMA=$(echo "$BODY" | jq -r '.schema_version')
            echo "   ✓ Schema version: $SCHEMA"
        fi
        if echo "$BODY" | jq -e '.stats' > /dev/null 2>&1; then
            TOTAL=$(echo "$BODY" | jq '.stats.total')
            ACTIVE=$(echo "$BODY" | jq '.stats.active')
            echo "   ✓ Stats: $TOTAL total, $ACTIVE active"
        fi
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 5: API Status endpoint (requires auth)
echo "5️⃣  GET /api/status"
RESPONSE=$(curl -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/api/status")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        PHASE=$(echo "$BODY" | jq -r '.phase // "unknown"')
        LOCKED=$(echo "$BODY" | jq -r '.locked // "unknown"')
        echo "   ✓ Phase: $PHASE, Locked: $LOCKED"
    else
        echo "   $BODY"
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 6: API Log endpoint (requires auth)
echo "6️⃣  GET /api/log"
RESPONSE=$(curl -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/api/log?count=10")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        LOG_COUNT=$(echo "$BODY" | jq '.count // 0')
        echo "   ✓ $LOG_COUNT log entries returned"
    else
        echo "   $BODY"
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

# Test 7: Manual discovery trigger (POST, requires auth)
echo "7️⃣  POST /api/discover"
RESPONSE=$(curl -X POST -s -w "\n%{http_code}" ${AUTH_HEADER} "$URL/api/discover")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "200" ]; then
    echo "   ✅ 200 OK"
    if [ "$JQ_AVAILABLE" = true ]; then
        if echo "$BODY" | jq -e '.success' > /dev/null 2>&1; then
            echo "   ✓ Discovery triggered successfully"
        fi
    else
        echo "   $BODY"
    fi
else
    # 202 is also acceptable (processing)
    if [ "$HTTP_CODE" == "202" ]; then
        echo "   ✅ 202 Accepted (processing)"
    else
        echo "   ❌ HTTP $HTTP_CODE"
        echo "   $BODY"
        ((FAILED++))
    fi
fi
echo ""

# Test 8: Submit deal endpoint (POST, requires auth)
echo "8️⃣  POST /api/submit"
TEST_CODE="VERIFY$(date +%s)"
RESPONSE=$(curl -X POST \
    -H "Content-Type: application/json" \
    ${AUTH_HEADER} \
    -d "{\"code\":\"$TEST_CODE\",\"url\":\"https://verify.com\",\"source\":\"test\",\"metadata\":{\"title\":\"Test\",\"reward\":{\"type\":\"cash\",\"value\":50}}}" \
    -s -w "\n%{http_code}" \
    "$URL/api/submit")
HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" == "201" ]; then
    echo "   ✅ 201 Created"
    if [ "$JQ_AVAILABLE" = true ]; then
        DEAL_ID=$(echo "$BODY" | jq -r '.deal_id // "unknown"')
        echo "   ✓ Deal created: $DEAL_ID"
    else
        echo "   $BODY"
    fi
else
    echo "   ❌ HTTP $HTTP_CODE"
    echo "   $BODY"
    ((FAILED++))
fi
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Summary
if [ $FAILED -eq 0 ]; then
    echo ""
    echo "✅ ALL 8 ENDPOINTS VERIFIED SUCCESSFULLY!"
    echo ""
    echo "Environment: $ENV"
    echo "URL: $URL"
    echo ""
    echo "Next steps:"
    echo "  • Check Cloudflare Dashboard for trigger configuration"
    echo "  • Monitor /health endpoint regularly"
    echo "  • Set up optional secrets (GITHUB_TOKEN, TELEGRAM)"
    exit 0
else
    echo ""
    echo "❌ $FAILED ENDPOINT(S) FAILED"
    echo ""
    echo "Check the logs above for details."
    exit 1
fi
